name: "Bug report"
description: "The game crashed or something is not working as intended."
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: "Describe the bug"
            description: "A clear and concise description of what the bug is."
        validations:
            required: true
    -   type: textarea
        attributes:
            label: "Reproduction steps"
            description: "Steps to reproduce the behavior."
        validations:
            required: true
    -   type: textarea
        attributes:
            label: "Screenshots"
            description: "If applicable, attach screenshots or videos to help explain your problem."
        validations:
            required: false
    -   type: textarea
        attributes:
            label: "Logs & crash-reports"
            description: "If applicable, provide a crash-report or the latest log."
        validations:
            required: false
    -   type: input
        attributes:
            label: "Mod pack version"
            description: "The mod pack version you were using. (e.g. v6.0)"
        validations:
            required: true
